name: 🚀 Deploy website on push


on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: 🔨 Build Project
      run: |
        npm install --save --force --legacy--peer-deps
        npm install -g @angular/cli@19.2.1
        ng build

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{secrets.bizzbean}}
        username: bizzbsncdz
        password: ${{secrets.ftp_password}}
        local-dir: ./dist/Bizzbean/browser/
        server-dir: ./public_html/uat.dashboard.bizzbean.com/

